### ISSUE TITLE
[Enhancement] Option to delete duplicated links

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extension-LinkUtilities#25]
Hi, nice plugin :)

After using the link renamer I ended up with two copies of Steam and two copies of Official Website.

So another thing that might fall into the scope of this plugin is the option to delete duplicate links (either by name, url, or both).

**Comment by HerrKnarz** [comment]
Great idea! I just have added the feature in version 1.7.
