### ISSUE TITLE
[Enhancement] Option to sort matching rules

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extension-LinkUtilities#29]
In the bookmarklet/remove link/rename link tabs of the config, it would be helpful to be able to manually re-order the rules without deleting and re-entering it.

Assuming that renaming starts with the first rule and goes down the list, it'd allow for a _bit_ more nuance of what order the links are matched. 

For the other tabs, it just would be nice to be able to sort them into alphabetical order. 

Thanks in advance. :)

**Comment by HerrKnarz** [comment]
With the upcoming version 1.8 you can sort all lists in the settings alphabetically except the renaming rules, which will be sorted by a newly added position field.
