### ISSUE TITLE
[Bug] Bookmarklet changes order of existing links

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extension-LinkUtilities#31]
**Describe the bug**
When I use the bookmarklet to add a link to the current game, the links get alphabetized (e.g. Official Website, Steam, PCGamingWiki becomes IGDB, Official Website, PCGamingWiki, Steam).

**To Reproduce**
1. Create a bookmarklet rule with name IGDB and rule `https://www.igdb.com/games/*`
2.  Add the bookmarklet linked from [this page](https://github.com/HerrKnarz/Playnite-Extension-LinkUtilities/wiki/URL-handler-and-bookmarklet) to the browser (for replication Vivaldi 5.6.2867.50).
3. Open an IGDB link and click the bookmarklet.

Further information for replication:

- Sorting order in extension preferences: Official Website (1), GOG (2), Steam (3), Epic Games (4), Origin (5), itch.io (6), IGDB (7), Wiki (8), PCGamingWiki (9). 
- Rename pattern, name 'IGDB,' pattern `*igdb.com*`
- Remove duplicate links activated, link name & url match.

**Expected behavior**
The links to remain in order, and IGDB to be added either in its preferred sort position or to the end.

**please complete the following information:**
 - Windows version:  Win10 Home, 64-bit, build 19045
 - Playnite version: 10.9
 - Extension version: 1.7.2

**Comment by chocolatechipcats** [comment]
Slight error on my part: It doesn't _reverse_ the order of links, but alphabetizes them. I'll correct the OP.

**Comment by HerrKnarz** [comment]
fixed in the upcoming version 1.8
