### ISSUE TITLE
[Enhancement] Option to tag missing links

### ISSUE THREAD

**Issue by chocolatechipcats** [HerrKnarz/Playnite-Extension-LinkUtilities#33]
**Is your feature request related to a problem? Please describe.**
Adding IGDB links to all my games (hopefully the 403 error gets resolved soon, but the bookmarklet helps!), but it's easy to lose track of which ones already have it.

**Describe the solution you'd like**
An option to check all games with a link of a specific pattern, then add a tag along the lines of `[Link: LinkTitle missing]` if they're missing. Preferably run only on-demand.

Additionally, a 'missing library link' may be useful for some users.

Thanks :)

**Comment by HerrKnarz** [comment]
I added that feature with version 2.0. The missing library link will in many cases already be present if the library site is in the missing links list. But I'll think about it. Closing this one here for now.
